import { test, expect } from '@playwright/test';
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
let js,css;
test.beforeAll(async()=>{const r=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import App from './web/src/App.jsx';import './web/src/index.css';createRoot(document.getElementById('root')).render(<App/>);`,resolveDir:fileURLToPath(new URL('..',import.meta.url)),loader:'jsx'},bundle:true,write:false,outdir:'/virtual',format:'iife',logLevel:'silent'});js=r.outputFiles.find(f=>f.path.endsWith('.js')).text;css=r.outputFiles.find(f=>f.path.endsWith('.css')).text;});
async function setup(page,validate){let posts=[];await page.route('**/*',r=>r.request().url()==='http://workbench.test/'?r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}):r.fulfill({json:{}}));await page.routeWebSocket('**/ws',()=>{});await page.route('**/api/robot/status',r=>r.fulfill({json:{robotOnline:true,mqttConnected:true,application:'cooperative-v1',build:'mbot-av-control-v1',capabilities:['wait','stop','turn_left'],armed:true,motion_enabled:true}}));await page.route('**/api/robot/program/validate',async r=>{posts.push(r.request().postDataJSON());return validate?validate(r):r.fulfill({json:{runnable:true,compiledCount:1,expandedCount:1,wireBytes:150}})});await page.addInitScript(()=>{localStorage.setItem('mbot-studio-current-profile','profile_default');localStorage.setItem('mbot-studio-current-project:profile_default','test');localStorage.setItem('mbot-studio-projects:profile_default',JSON.stringify([{id:'test',name:'Bench',blocks:[{type:'wait',duration:1}]}]));});await page.goto('http://workbench.test/');await page.addStyleTag({content:css});await page.addScriptTag({content:js});await expect(page.locator('.scratch-editor')).toBeVisible();return posts;}
test('App retains advertised capabilities for its Robot-ready palette',async({page})=>{await setup(page);await expect(page.getByRole('button',{name:'Add turn left',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Add stop motors & sound',exact:true})).toBeVisible();});
test('workspace is primary; helper toggles without losing program and fits tablet',async({page})=>{await setup(page);await expect(page.locator('.chat-panel-container')).toBeHidden();await page.getByRole('button',{name:'AI helper',exact:true}).click();await expect(page.locator('.chat-panel-container')).toBeVisible();await page.getByRole('button',{name:'AI helper',exact:true}).click();await expect(page.locator('.se-script.main')).toContainText('wait');await page.setViewportSize({width:900,height:800});const run=await page.getByRole('button',{name:'Run Program'}).boundingBox();expect(run.x+run.width).toBeLessThanOrEqual(900);await page.screenshot({path:test.info().outputPath('workbench-tablet.png')});});
test('read-only preflight explains rejection and disables Run without publishing',async({page})=>{let publications=0;await page.route('**/api/robot/program',r=>{publications++;return r.fulfill({json:{}})});await setup(page,r=>r.fulfill({status:422,json:{runnable:false,error:'Block 1: unsupported sensor_distance'}}));await expect(page.getByTestId('program-readiness')).toContainText('unsupported sensor_distance');await expect(page.getByRole('button',{name:'Run Program'})).toBeDisabled();expect(publications).toBe(0);});
test('old preflight cannot replace newer block validation',async({page})=>{let release;const posts=await setup(page,async r=>{if(r.request().postDataJSON().program[0].duration===1){await new Promise(resolve=>release=resolve);return r.fulfill({json:{runnable:true,compiledCount:1,expandedCount:1}});}return r.fulfill({status:400,json:{runnable:false,error:'New value invalid'}});});await expect.poll(()=>Boolean(release)).toBe(true);await page.locator('.se-script.main input[type="number"]').fill('99');await expect(page.getByTestId('program-readiness')).toContainText('New value invalid');release();await page.waitForTimeout(300);await expect(page.getByTestId('program-readiness')).toContainText('New value invalid');await expect(page.getByRole('button',{name:'Run Program'})).toBeDisabled();expect(posts.length).toBeGreaterThan(1);});
