import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
let js,css;
test.beforeAll(async()=>{const r=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import App from './web/src/App.jsx';import './web/src/index.css';createRoot(document.getElementById('root')).render(<App/>);`,resolveDir:fileURLToPath(new URL('..',import.meta.url)),loader:'jsx'},bundle:true,write:false,outdir:'/virtual',format:'iife',logLevel:'silent'});js=r.outputFiles.find(f=>f.path.endsWith('.js')).text;css=r.outputFiles.find(f=>f.path.endsWith('.css')).text;});
async function setup(page){const requests=[];await page.route('**/*',r=>{requests.push({url:r.request().url(),method:r.request().method()});return r.request().url()==='http://diagnostics.test/'?r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}):r.fulfill({json:{}})});await page.routeWebSocket('**/ws',()=>{});await page.addInitScript(()=>localStorage.setItem('mbot-studio-current-profile','profile_default'));await page.goto('http://diagnostics.test/');await page.addStyleTag({content:css});await page.addScriptTag({content:js});return requests;}
test('diagnostics is available while offline and only reads server evidence on demand',async({page})=>{const requests=await setup(page);await expect(page.getByRole('button',{name:'Robot diagnostics',exact:true})).toBeVisible();expect(requests.filter(r=>r.url.endsWith('/api/robot/diagnostics'))).toEqual([]);await page.getByRole('button',{name:'Robot diagnostics',exact:true}).click();await expect(page.getByRole('dialog',{name:'Robot diagnostics'})).toBeVisible();await expect(page.getByRole('dialog')).toContainText('does not establish a battery protection cutoff');await expect(page.getByRole('button',{name:'Download diagnostic report'})).toBeVisible();expect(requests.filter(r=>r.method==='POST')).toEqual([]);await page.getByRole('button',{name:'Close diagnostics'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);});

test('report downloads exact retained evidence and shows recorder disk failure honestly',async({page})=>{await setup(page);const report={schemaVersion:1,recording:{healthy:false,lastError:'EACCES'},lastKnown:{sensors:{payload:{battery:50},receivedAt:1700000000000,ageMs:25000}},events:[{id:'one',time:1700000001000,kind:'publish_intent',data:{run_id:'run-one',type:'turn_right'}}]};await page.route('**/api/robot/diagnostics',r=>r.fulfill({json:report}));await page.getByRole('button',{name:'Robot diagnostics',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('EACCES');await expect(page.getByRole('dialog')).toContainText('Last received battery: 50%');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download diagnostic report'}).click();const file=await download;const fs=await import('node:fs/promises');expect(JSON.parse(await fs.readFile(await file.path(),'utf8'))).toEqual(report);await page.screenshot({path:test.info().outputPath('diagnostics.png')});});
test('failed report refresh never downloads a stale response and a subsequent refresh recovers',async({page})=>{await setup(page);let failed=true;await page.route('**/api/robot/diagnostics',r=>failed?r.fulfill({status:500,json:{error:'disk'}}):r.fulfill({json:{recording:{healthy:true},events:[]}}));await page.getByRole('button',{name:'Robot diagnostics',exact:true}).click();await expect(page.getByRole('alert')).toContainText('HTTP 500');await expect(page.getByRole('button',{name:'Download diagnostic report'})).toBeDisabled();failed=false;await page.getByRole('button',{name:'Refresh report'}).click();await expect(page.getByRole('dialog')).toContainText('Recorder healthy');await expect(page.getByRole('button',{name:'Download diagnostic report'})).toBeEnabled();});

test('emergency Stop remains accessible while diagnostics modal is open',async({page})=>{await setup(page);let stops=0;await page.route('**/api/robot/stop',r=>{stops++;return r.fulfill({json:{sent:true}})});await page.getByRole('button',{name:'Robot diagnostics',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Emergency Stop',exact:true}).click();await expect.poll(()=>stops).toBe(1);await expect(page.getByRole('dialog')).toBeVisible();});
